#!/usr/bin/env node
/**
 * build-index — generates the two machine-readable indexes from document
 * frontmatter. Both are derived; neither is ever hand-edited.
 *
 *   index/manifest.tsv    one line per document, built to be GREPPED
 *   index/watchers.json   source file → documents that cite it
 *
 * WHY A MANIFEST INSTEAD OF A README TABLE:
 *
 * The skill used to read the whole index into context on every lookup. That
 * costs tokens proportional to the size of the corpus — fine at twenty
 * documents, ruinous at a thousand, and it gets worse precisely as the system
 * succeeds.
 *
 * One line per document, with the keywords on that line, means the assistant
 * can grep for a term and get back the three matching rows instead of the whole
 * table. Retrieval cost stops depending on how many documents exist.
 *
 * Columns are tab-separated so a single grep hit is self-describing:
 *   path  kind  domain  repos  status  keywords
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';

const DOC_ROOT = 'docs';

function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return null;
  const end = text.indexOf('\n---', 3);
  if (end === -1) return null;

  const meta = { sources: [] };
  let current = null;

  for (const line of text.slice(4, end + 1).split('\n')) {
    if (!line.trim()) continue;
    const item = line.match(/^\s*-\s+(\w+):\s*(.+?)\s*$/);
    if (item) { current = { [item[1]]: item[2] }; meta.sources.push(current); continue; }
    const nested = line.match(/^\s{4,}(\w+):\s*(.+?)\s*$/);
    if (nested && current) { current[nested[1]] = nested[2]; continue; }
    const top = line.match(/^(\w+):\s*(.*?)\s*$/);
    if (top) { current = null; if (top[1] !== 'sources') meta[top[1]] = top[2]; }
  }
  return meta;
}

/** First `# Heading` is the document's title; first paragraph after it is the summary. */
function titleAndSummary(text) {
  const body = text.slice(text.indexOf('\n---', 3) + 4);
  const title = body.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? '';
  const after = title ? body.slice(body.indexOf(title) + title.length) : body;
  const summary = after.split('\n').map((l) => l.trim())
    .find((l) => l && !l.startsWith('#') && !l.startsWith('---')) ?? '';
  return { title, summary };
}

async function findDocs(dir) {
  const out = [];
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await findDocs(full)));
    else if (e.name.endsWith('.md') && e.name !== 'README.md') out.push(full);
  }
  return out;
}

const root = resolve(process.cwd());
const docs = (await findDocs(join(root, DOC_ROOT))).sort();

const rows = [];
const watchers = {};
const problems = [];

for (const file of docs) {
  const rel = relative(root, file);
  const text = readFileSync(file, 'utf8');
  const meta = parseFrontmatter(text);

  if (!meta) { problems.push(`${rel}: no frontmatter`); continue; }
  for (const required of ['kind', 'domain', 'keywords', 'status']) {
    if (!meta[required]) problems.push(`${rel}: missing \`${required}\``);
  }
  if (meta.sources.length > 15) {
    problems.push(`${rel}: ${meta.sources.length} sources — keep it under 15 or the flags become noise`);
  }

  const { title, summary } = titleAndSummary(text);
  const repos = [...new Set(meta.sources.map((s) => s.repo))].sort().join(',');

  // tabs separate columns, so every value must be tab-free
  const clean = (v) => String(v ?? '').replace(/\s+/g, ' ').trim();

  rows.push([
    rel, meta.kind, meta.domain, repos, meta.status,
    clean(title), clean(meta.keywords), clean(summary).slice(0, 160),
  ].map(clean).join('\t'));

  for (const src of meta.sources) {
    if (!src.repo || !src.path) continue;
    (watchers[`${src.repo}/${src.path}`] ??= []).push(rel);
  }
}

mkdirSync('index', { recursive: true });

const header = [
  '# GENERATED by tools/build-index.mjs — do not edit.',
  '# Grep this file; do not read it whole. Columns are tab-separated:',
  '# path  kind  domain  repos  status  title  keywords  summary',
].join('\n');

writeFileSync('index/manifest.tsv', header + '\n' + rows.join('\n') + '\n', 'utf8');

const sorted = Object.fromEntries(
  Object.keys(watchers).sort().map((k) => [k, [...new Set(watchers[k])].sort()]),
);
writeFileSync('index/watchers.json', JSON.stringify(sorted, null, 2) + '\n', 'utf8');

const bytes = Buffer.byteLength(rows.join('\n'));
console.log(`index/manifest.tsv   ${rows.length} document(s), ${bytes} bytes`);
console.log(`index/watchers.json  ${Object.keys(sorted).length} watched file(s)`);
console.log(`\na keyword grep returns matching rows only — roughly ${Math.round(bytes / Math.max(rows.length, 1))} bytes each,`);
console.log(`independent of how many documents the repository holds.`);

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
